### ISSUE TITLE
Outdated Age

### ISSUE THREAD

**Issue by HorridModz** [WerWolv/WerWolv#1]
Your age is outdated by a year 😜 . I just thought I'd point it out in case you want to fix it!

**Comment by WerWolv** [comment]
Ha thank you! I completely forgot about this repo :D
I wish this could be automated somehow

**Comment by HorridModz** [comment]
> Ha thank you! I completely forgot about this repo :D I wish this could be automated somehow

You can use a cloud hosting service to run a script that updates your repository every year (though this is extreme overkill).
